<a href="https://colab.research.google.com/github/ShrieyaDesai/ML/blob/main/Create%20%26%20Display.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Code1:

from sklearn import datasets
import pandas as pd

In [5]:
print('THIS IS  THE PROGRAM TO ACCESS  IRIS DATASET')
iris=datasets.load_iris()
print(" To print the description of Iris Dataset")
print(iris.DESCR)

print('\n\n\n\n')

# df will fold dataset as a table
df=pd.DataFrame(
   iris.data,
   columns=iris.feature_names
   )

#labels are assigned to df[target] table or array
df['target']=pd.Series(
    iris.target
   )

df['target_names']=df['target'].apply(lambda y:iris.target_names[y])

print('To display First 5 samples')

# df.head(5) will return the first five samples in the dataset
print(df.head(5))

print('To display randomply 5 samples')
#df.sample(5) will return randomly five samples from the dataset
print(df.sample(5))

THIS IS  THE PROGRAM TO ACCESS  IRIS DATASET
 To print the description of Iris Dataset
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...






To display First 5 samples
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   target target_names
0       0       setosa
1       0       setosa
2       0       setosa
3       0       setosa
4       0       setosa
To display randomply 5 samples
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
22                 4.6               3.6                1.0               0.2
119                6.0               2.2                5.0               1.5
50                 7.0               3.2                4.7               1.4
17                 5.1               3.5                1.4               0.3
59                 5.2               2.7                3.9               1.4

     target target_names
22        0       setosa
119       2    virginica
50        1   versicolor
17        0       setosa
59        1   versicolor

In [ ]:
# Train Test Split Ratio
from sklearn.model_selection import train_test_split

df_train,df_test=train_test_split(df,test_size=0.3) # For 70: 30 Split

print('The total number of samples in the dataset = ',df.shape[0])
print('The number of samples  in training set = ',df_train.shape[0])
print('The number of samples  in testing set = ',df_test.shape[0])

print('The first five samples of training set')
print(df_train.head(5))

print('\n\nThe first five samples of testing set')
print(df_test.head(5))

The total number of samples in the dataset =  150
The number of samples  in training set =  105
The number of samples  in testing set =  45
The first five samples of training set
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
35                5.0               3.2                1.2               0.2
45                4.8               3.0                1.4               0.3
82                5.8               2.7                3.9               1.2
17                5.1               3.5                1.4               0.3
33                5.5               4.2                1.4               0.2

    target target_names
35       0       setosa
45       0       setosa
82       1   versicolor
17       0       setosa
33       0       setosa


The first five samples of testing set
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
5                  5.4               3.9                1.7               0.4
120                6.9               3.2                5.7               2.3
51                 6.4               3.2                4.5               1.5
133                6.3               2.8                5.1               1.5
56                 6.3               3.3                4.7               1.6

     target target_names
5         0       setosa
120       2    virginica
51        1   versicolor
133       2    virginica
56        1   versicolor

In [6]:
#Code2:
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [7]:

# load the iris dataset
iris = datasets.load_iris()
df = pd.DataFrame(iris.data)
label = pd.DataFrame(iris.target)


# Let us split 70% for Training and 30% for Testing

X_train, X_test, y_train, y_test = train_test_split(df, label,test_size=0.3,shuffle = True)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.3,shuffle= True)

print(" Totoal number of samples in the Dataset  ", df.shape[0])
print(" Total number of labels in the Dataset ", label.shape[0])

print(" Total number of samples in training set X_train ", X_train.shape[0])
print(" Total number of labels in training set y_train " , y_train.shape[0])

print(" Total number of samples in testing set X_test ", X_test.shape[0])
print(" Total number of labels in testing set y_test " , y_test.shape[0])

print(" Total number of samples in validation set X_test ", X_val.shape[0])
print(" Total number of labels in validation set  y_test " , y_val.shape[0])

print('The 3 samples of training set')
print(X_train.head(3))
print('The random 3 samples of training set')
print(X_train.sample(3))

print('The 3 samples of testing set')
print(X_test.head(3))
print('The random 3 samples of testing set')
print(X_test.sample(3))

print('The 3 samples of validation set')
print(X_val.head(3))
print('The random 3 samples of validation set')
print(X_val.sample(3))

 Totoal number of samples in the Dataset   150
 Total number of labels in the Dataset  150
 Total number of samples in training set X_train  73
 Total number of labels in training set y_train  73
 Total number of samples in testing set X_test  45
 Total number of labels in testing set y_test  45
 Total number of samples in validation set X_test  32
 Total number of labels in validation set  y_test  32
The 3 samples of training set
       0    1    2    3
12   4.8  3.0  1.4  0.1
129  7.2  3.0  5.8  1.6
102  7.1  3.0  5.9  2.1
The random 3 samples of training set
       0    1    2    3
64   5.6  2.9  3.6  1.3
12   4.8  3.0  1.4  0.1
116  6.5  3.0  5.5  1.8
The 3 samples of testing set
       0    1    2    3
119  6.0  2.2  5.0  1.5
17   5.1  3.5  1.4  0.3
18   5.7  3.8  1.7  0.3
The random 3 samples of testing set
       0    1    2    3
117  7.7  3.8  6.7  2.2
72   6.3  2.5  4.9  1.5
29   4.7  3.2  1.6  0.2
The 3 samples of validation set
       0    1    2    3
137  6.4  3.1  5.5  1.8
138  6.0  3.0  4.8  1.8
28   5.2  3.4  1.4  0.2
The random 3 samples of validation set
       0    1    2    3
134  6.1  2.6  5.6  1.4
88   5.6  3.0  4.1  1.3
35   5.0  3.2  1.2  0.2